### ISSUE TITLE
Formulario Web

### ISSUE THREAD

**Issue by llhh45gh** [llhh45gh/trabajoPraIntGf#18]
cambie el anterior e inserte uno que integra HTML, CSS y JS, con las lineas de codigo respectivas, de acuerdo a lo solicitado en el trabajo.

**Comment by avanciniestrella** [comment]
Hice correcciones al formulario de contacto de acuerdo a las indicaciones de la profesora, en cuanto al script en el <head>, al correspondiente archivo JS. EmailJS lo utilicé para dar funcionalidad al formulario,  para que al llenar el formulario los datos vayan a una cuenta de mail.
