### ISSUE TITLE
web Form

### ISSUE THREAD

**Issue by llhh45gh** [llhh45gh/trabajoPraIntGf#20]
Introduccion de Nuevo Web Form : con lineas de codigo en HTML, CSS y JS.-

**Comment by avanciniestrella** [comment]
Hice correcciones al formulario de contacto de acuerdo a las indicaciones de la profesora, en cuanto al script en el <head>, al correspondiente archivo JS. EmailJS lo utilicé para dar funcionalidad al formulario,  para que al llenar el formulario los datos vayan a una cuenta de mail.
